name: heatlth_monitor
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.0-134.5.beta <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  firebase_auth: ^3.3.10
  firebase_core: ^1.13.1
  cloud_firestore: ^3.1.10
  google_sign_in: ^5.2.4
  firebase_database: ^9.0.8
  google_fonts: ^2.3.1
  flutter_svg: ^1.0.3
  flutter_screenutil: ^5.3.1
  flutter_spinkit: ^5.1.0
  animated_splash_screen: ^1.2.0
  page_transition: ^2.0.5
  rounded_loading_button: ^2.1.0
  avatar_glow: ^2.0.2
  date_format: ^2.0.5
  syncfusion_flutter_charts: ^19.4.56
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2
  lints: 1.0.1
  flutter_test: 
    sdk: flutter
flutter_icons:
  android: true
  ios: true
  image_path: "assets/appIcon.png"

flutter: 
  uses-material-design: true
  assets:
    - assets/
    - assets/appLogo.png
    - assets/appIcon.png


